# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculator_pb2 as calculator__pb2


class CalculateStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CalculateAdd = channel.unary_unary(
        '/calculator.Calculate/CalculateAdd',
        request_serializer=calculator__pb2.CalculateRequest.SerializeToString,
        response_deserializer=calculator__pb2.CalculateReply.FromString,
        )


class CalculateServicer(object):
  """The greeting service definition.
  """

  def CalculateAdd(self, request, context):
    """sends a calculating
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculateServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CalculateAdd': grpc.unary_unary_rpc_method_handler(
          servicer.CalculateAdd,
          request_deserializer=calculator__pb2.CalculateRequest.FromString,
          response_serializer=calculator__pb2.CalculateReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'calculator.Calculate', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
