# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='calculator',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63\x61lculator.proto\x12\ncalculator\"2\n\x10\x43\x61lculateRequest\x12\x0e\n\x06input1\x18\x01 \x01(\x01\x12\x0e\n\x06input2\x18\x02 \x01(\x01\" \n\x0e\x43\x61lculateReply\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32W\n\tCalculate\x12J\n\x0c\x43\x61lculateAdd\x12\x1c.calculator.CalculateRequest\x1a\x1a.calculator.CalculateReply\"\x00\x42\x36\n\x1bio.grpc.examples.calculatorB\x0f\x43\x61lculatorProtoP\x01\xa2\x02\x03\x43LPb\x06proto3')
)




_CALCULATEREQUEST = _descriptor.Descriptor(
  name='CalculateRequest',
  full_name='calculator.CalculateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input1', full_name='calculator.CalculateRequest.input1', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input2', full_name='calculator.CalculateRequest.input2', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=82,
)


_CALCULATEREPLY = _descriptor.Descriptor(
  name='CalculateReply',
  full_name='calculator.CalculateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='calculator.CalculateReply.result', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['CalculateRequest'] = _CALCULATEREQUEST
DESCRIPTOR.message_types_by_name['CalculateReply'] = _CALCULATEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalculateRequest = _reflection.GeneratedProtocolMessageType('CalculateRequest', (_message.Message,), dict(
  DESCRIPTOR = _CALCULATEREQUEST,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.CalculateRequest)
  ))
_sym_db.RegisterMessage(CalculateRequest)

CalculateReply = _reflection.GeneratedProtocolMessageType('CalculateReply', (_message.Message,), dict(
  DESCRIPTOR = _CALCULATEREPLY,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.CalculateReply)
  ))
_sym_db.RegisterMessage(CalculateReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033io.grpc.examples.calculatorB\017CalculatorProtoP\001\242\002\003CLP'))

_CALCULATE = _descriptor.ServiceDescriptor(
  name='Calculate',
  full_name='calculator.Calculate',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=118,
  serialized_end=205,
  methods=[
  _descriptor.MethodDescriptor(
    name='CalculateAdd',
    full_name='calculator.Calculate.CalculateAdd',
    index=0,
    containing_service=None,
    input_type=_CALCULATEREQUEST,
    output_type=_CALCULATEREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATE)

DESCRIPTOR.services_by_name['Calculate'] = _CALCULATE

# @@protoc_insertion_point(module_scope)
